config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:create, :new, :destroy]
  resources :circles, only: [:create, :edit, :update, :new, :destroy]

  resource :user, only: [:create, :new, :update, :edit] do
    get "feed", on: :member
    resources :circles, only: [:index, :show]
  end

  resources :posts, only: [:create, :new, :show] do
    resources :comments, only: :create
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to(
    :commenter,
    class_name: "User",
    foreign_key: :commenter_id,
    primary_key: :id,
    inverse_of: :comments
  )

  belongs_to(
    :post,
    class_name: "Post",
    foreign_key: :post_id,
    primary_key: :id,
    inverse_of: :comments
  )

  validates :body, :commenter_id, :post_id, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :require_signed_in!

  def create
    @comment = current_user.comments.build(comment_params)
    flash[:errors] = @comment.errors.full_messages unless @comment.save
    redirect_to post_url(@comment.post_id)
  end

  private

  def comment_params
    params.require(:comment).permit(:body).merge(post_id: params[:post_id])
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comments.html.erb
<% @post.comments.each do |comment| %>
<div>
  <h4><%= comment.commenter.email %>:</h4>
  <h5>@<%= comment.updated_at %></h5>
  <p><%= comment.body %></p>
</div>
<hr>
<% end %>

app/views/comments/_form.html.erb
<form action="<%= post_comments_url(@post) %>" method="post">
  <%= authenticity_token %>

  <label>Comment:<br>
    <textarea name="comment[body]"></textarea>
  </label><br>

  <button>Publish</button>
</form>