config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:create, :new, :destroy]
  resources :circles, only: [:create, :edit, :update, :new, :destroy]

  resource :user, only: [:create, :new, :update, :edit] do
    get "feed", on: :member
    resources :circles, only: [:index, :show]
  end

  resources :posts, only: [:create, :new, :show] do
    resources :comments, only: :create
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many(
    :memberships,
    class_name: "CircleMembership",
    foreign_key: :member_id,
    primary_key: :id,
    inverse_of: :member
  )

  has_many(
    :belong_to_circles,
    through: :memberships,
    source: :circle
  )

  has_many(
    :owned_circles,
    class_name: "Circle",
    foreign_key: :owner_id,
    primary_key: :id,
    inverse_of: :owner
  )

  has_many(
    :posts,
    class_name: "Post",
    foreign_key: :author_id,
    primary_key: :id,
    inverse_of: :author
  )

  has_many(
    :comments,
    class_name: "Comment",
    foreign_key: :commenter_id,
    primary_key: :id,
    inverse_of: :commenter
  )

  validates :email, :password_digest, :session_token, presence: true
  validates :email, :session_token, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  def self.find_by_credentials(email, password)
    user = User.find_by_email(email)
    return if user.nil?
    user.is_password?(password) ? user : nil
  end

  after_initialize :ensure_session_token
  attr_reader :password

  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
    @password = password
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64(16)
    save!
    self.session_token
  end

  private

  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64(16)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_signed_in!, except: [:create, :new]

  def feed
    belong_to_circles = current_user.belong_to_circles

    @friend_posts = belong_to_circles.each_with_object([]) do |circle, posts|
      circle.shared_posts.each { |post| posts << post }
    end

    @friend_posts.sort! { |post1, post2| post2.updated_at <=> post1.updated_at }
    render :feed
  end

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in!(@user)
      redirect_to feed_user_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def new
    @user = User.new
    render :new
  end

  def update
    @user = current_user

    if @user.update(user_params)
      redirect_to feed_user_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :edit
    end
  end

  def edit
    @user = current_user
    render :edit
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_fields.html.erb
<%= authenticity_token %>

<label>Email:
  <input type="text" name="user[email]" value="<%= @user.email %>">
</label><br>

<label>Password:
  <input type="password" name="user[password]" value="">
</label><br>

app/views/users/edit.html.erb
<h2>Edit user</h2>

<form action="<%= user_url %>" method="post">
  <input type="hidden" name="_method" value="put">
  <%= render "fields" %>
  <button>Update</button>
</form>

app/views/users/feed.html.erb
<h2>Feed</h2>
<a href="<%= new_post_url %>">New post</a>
<hr>

<% @friend_posts.each do |post| %>
<div>
  <h3><%= post.author.email %>:</h3>
  <h5>@<%= post.created_at %></h5>
  <h4><a href="<%= post_url(post) %>"><%= post.title %></a></h4>
  <div><%= post.body %></div>
</div>
<ul>
  <% post.links.each do |link| %>
  <li><a href="#"><%= link.url %></a></li>
  <% end %>
</ul>
<hr>
<% end %>

app/views/users/new.html.erb
<h2>Sign up</h2>

<form action="<%= user_url %>" method="post">
  <%= render "fields" %>
  <button>Sign up</button>
</form>

Already a user? Click <a href="<%= new_session_url %>">here</a> to sign in.