config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:create, :new, :destroy]
  resources :circles, only: [:create, :edit, :update, :new, :destroy]

  resource :user, only: [:create, :new, :update, :edit] do
    get "feed", on: :member
    resources :circles, only: [:index, :show]
  end

  resources :posts, only: [:create, :new, :show] do
    resources :comments, only: :create
  end
end

app/models/circle.rb
class Circle < ActiveRecord::Base
  has_many(
    :memberships,
    class_name: "CircleMembership",
    foreign_key: :circle_id,
    primary_key: :id,
    dependent: :destroy,
    inverse_of: :circle
  )

  has_many(
    :members,
    through: :memberships,
    source: :member
  )

  belongs_to(
    :owner,
    class_name: "User",
    foreign_key: :owner_id,
    primary_key: :id,
    inverse_of: :owned_circles
  )

  has_many(
    :shares,
    class_name: "PostShare",
    foreign_key: :circle_id,
    primary_key: :id,
    dependent: :destroy,
    inverse_of: :circle
  )

  has_many(
    :shared_posts,
    through: :shares,
    source: :post
  )

  validates :name, :owner_id, presence: true
  validates :name, uniqueness: { scope: :owner_id }
end

app/controllers/circles_controller.rb
class CirclesController < ApplicationController
  before_filter :require_signed_in!

  def index
    @circles = current_user.owned_circles
  end

  def show
    @circle = Circle.find(params[:id])
    render :show
  end

  def create
    @circle = current_user.owned_circles.build(circle_params)

    if @circle.save
      redirect_to user_circle_url(@circle)
    else
      flash.now[:errors] = @circle.errors.full_messages
      render :new
    end
  end

  def new
    @circle = Circle.new
    render :new
  end

  def update
    @circle = Circle.find(params[:id])

    if @circle.update(circle_params)
      redirect_to user_circle_url(@circle)
    else
      flash.now[:errors] = @circle.errors.full_messages
      render :edit
    end
  end

  def edit
    @circle = Circle.find(params[:id])
    render :edit
  end

  def destroy
    @circle = Circle.find(params[:id])
    @circle.destroy
    redirect_to user_circles_url
  end

  private

  def circle_params
    params.require(:circle).permit(:name, member_ids: [])
  end

end

app/helpers/circles_helper.rb
module CirclesHelper
end

app/views/circles/_fields.html.erb
  <%= authenticity_token %>

  <label>Name:
    <input type="text" name="circle[name]" value="<%= @circle.name %>">
  </label><br>

<% User.all.each do |user| %>
  <% next if user == current_user %>
  <label><%= user.email %>
    <input type="checkbox" name="circle[member_ids][]" value="<%= user.id %>"
      <%= "checked" if @circle.members.include?(user) %>>
  </label><br>
<% end %>

  <input type="hidden" name="circle[member_ids][]"
    value="<%= current_user.id %>">
  <input type="hidden" name="circle[member_ids][]" value = "">

app/views/circles/edit.html.erb
<h2>Edit circle</h2>

<form action="<%= circle_url(@circle) %>" method="post">
  <input type="hidden" name="_method" value="put">
  <%= render "fields" %>
  <button>Update</button>
</form>

<form action="<%= circle_url(@circle) %>" method="post">
  <input type="hidden" name="_method" value="delete">
  <%= authenticity_token %>
  <button>Delete circle</button>
</form>

app/views/circles/index.html.erb
<h2>Your circles</h2>

<ul>
  <% @circles.each do |circle| %>
    <li><a href="<%= user_circle_url(circle) %>"><%= circle.name %></a></li>
  <% end %>
</ul>

<a href="<%= new_circle_url %>">New circle</a>

app/views/circles/new.html.erb
<h2>New circle</h2>

<form action="<%= circles_url %>" method="post">
  <%= render "fields" %>
  <button>Create</button>
</form>

app/views/circles/show.html.erb
<a href="<%= user_circles_url %>">&laquo; Back</a>
<h2><%= @circle.name %></h2>

<ul>
<% @circle.members.each do |member| %>
  <li><a href="#"><%= member.email %></a></li>
<% end %>
</ul>

<a href="<%= edit_circle_url(@circle) %>">Edit</a>