config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:create, :new, :destroy]
  resources :circles, only: [:create, :edit, :update, :new, :destroy]

  resource :user, only: [:create, :new, :update, :edit] do
    get "feed", on: :member
    resources :circles, only: [:index, :show]
  end

  resources :posts, only: [:create, :new, :show] do
    resources :comments, only: :create
  end
end

app/views/layouts/_error_messages.html.erb
<% if flash[:errors] %>
  <ul>
  <% flash[:errors].each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
<% end %>

app/views/layouts/_header.html.erb
<% if signed_in? %>
  <div>
    <h3><a href="<%= feed_user_url %>"><%= current_user.email %></a></h3>
    <h5><a href="<%= edit_user_url %>">Edit</a></h5>
    <h4><a href="<%= user_circles_url %>">Your circles</a></h4>
    <form action="<%= session_url %>" method="post">
      <%= authenticity_token %>
      <input type="hidden" name="_method" value="delete">
      <button>Sign out</button>
    </form><br>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FriendCircle</title>
  <%= stylesheet_link_tag    'application', media: 'all',
    'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <h1>Friend Circles</h1>
  <%= render "layouts/header" %>
  <%= render "layouts/error_messages" %>
  <hr>

<%= yield %>

</body>
</html>